import jsPDF from 'jspdf';
export const PDF_CONFIG = {
  format: 'a4' as const,
  orientation: 'portrait' as const,
  unit: 'mm' as const,
  dimensions: {
    width: 210,
    height: 297,
  },
  margins: {
    top: 20,
    right: 15,
    bottom: 20,
    left: 15,
  },
  colors: {
    primary: '#1E40AF',
    secondary: '#10B981',
    text: '#1F2937',
    lightGray: '#F3F4F6',
    border: '#E5E7EB',
  },
  fonts: {
    title: 18,
    heading: 14,
    subheading: 12,
    body: 10,
    small: 8,
  },
};
export function formatDate(isoString: string): string {
  const date = new Date(isoString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}
export function addPageHeader(
  pdf: jsPDF,
  title: string,
  date: string,
  pageNumber: number
): void {
  const { margins, colors, fonts } = PDF_CONFIG;
  // Header background
  pdf.setFillColor(colors.primary);
  pdf.rect(0, 0, PDF_CONFIG.dimensions.width, 15, 'F');
  // Logo/Brand text
  pdf.setTextColor('#FFFFFF');
  pdf.setFontSize(fonts.heading);
  pdf.setFont('helvetica', 'bold');
  pdf.text('ApexSEO', margins.left, 10);
  // Title
  pdf.setFontSize(fonts.body);
  pdf.setFont('helvetica', 'normal');
  pdf.text(title, PDF_CONFIG.dimensions.width - margins.right, 10, { align: 'right' });
  // Reset text color
  pdf.setTextColor(colors.text);
}
export function addPageFooter(
  pdf: jsPDF,
  pageNumber: number,
  totalPages: number
): void {
  const { margins, colors, fonts, dimensions } = PDF_CONFIG;
  const footerY = dimensions.height - 10;
  // Footer line
  pdf.setDrawColor(colors.border);
  pdf.line(margins.left, footerY - 5, dimensions.width - margins.right, footerY - 5);
  // Page number
  pdf.setFontSize(fonts.small);
  pdf.setTextColor(colors.text);
  pdf.text(
    `Page ${pageNumber} of ${totalPages}`,
    dimensions.width / 2,
    footerY,
    { align: 'center' }
  );
  // Company info
  pdf.text('Generated by ApexSEO', dimensions.width - margins.right, footerY, { align: 'right' });
}
export function calculatePageBreaks(contentHeight: number): number {
  const { dimensions, margins } = PDF_CONFIG;
  const usableHeight = dimensions.height - margins.top - margins.bottom - 20; // 20mm for header/footer
  return Math.ceil(contentHeight / usableHeight);
}
export function drawTableRow(
  pdf: jsPDF,
  x: number,
  y: number,
  columns: { text: string; width: number }[],
  isHeader: boolean = false
): number {
  const { colors, fonts } = PDF_CONFIG;
  const rowHeight = 8;
  if (isHeader) {
    pdf.setFillColor(colors.lightGray);
    pdf.rect(x, y, columns.reduce((sum, col) => sum + col.width, 0), rowHeight, 'F');
    pdf.setFont('helvetica', 'bold');
  } else {
    pdf.setFont('helvetica', 'normal');
  }
  pdf.setFontSize(fonts.body);
  pdf.setTextColor(colors.text);
  let currentX = x;
  columns.forEach(col => {
    pdf.text(col.text, currentX + 2, y + 5);
    currentX += col.width;
  });
  return y + rowHeight;
}