import { Client, Lead, PipelineStage, UploadedFile } from './types';
const mockFiles: UploadedFile[] = [
    {
        id: 'file-001',
        clientId: 'cl-001',
        fileName: 'Q1_SEO_Audit.pdf',
        fileType: 'pdf',
        fileSize: 2048000, // 2MB
        uploadDate: '2023-02-20T10:00:00Z',
        url: '/mock/Q1_SEO_Audit.pdf',
    },
    {
        id: 'file-002',
        clientId: 'cl-001',
        fileName: 'Competitor_Keywords.csv',
        fileType: 'csv',
        fileSize: 512000, // 500KB
        uploadDate: '2023-03-10T14:30:00Z',
        url: '/mock/Competitor_Keywords.csv',
    },
];
export const MOCK_CLIENTS: Client[] = [
  {
    id: 'cl-001',
    company: 'Innovate Inc.',
    contactPerson: 'Alice Johnson',
    industry: 'Technology',
    website: 'https://innovateinc.com',
    email: 'alice.j@innovateinc.com',
    phone: '123-456-7890',
    createdAt: '2023-01-15T10:00:00Z',
    seoStats: {
      indexedKeywords: 1250,
      seoClicks: 8500,
      strategicTasks: [
        { id: 'task-1', task: 'Complete on-page audit', completed: true },
        { id: 'task-2', task: 'Develop Q3 content strategy', completed: false },
        { id: 'task-3', task: 'Build 10 high-authority backlinks', completed: false },
      ],
      competitors: ['TechSolutions', 'FutureGadgets'],
      longTailTargets: ['best AI-powered analytics tools for small business'],
      lowKeywordDifficultyTargets: ['innovative tech startup solutions 2024'],
      websiteQualityRating: 88,
    },
    uploadedFiles: mockFiles,
  },
  {
    id: 'cl-002',
    company: 'GreenLeaf Organics',
    contactPerson: 'Bob Williams',
    industry: 'E-commerce',
    website: 'https://greenleaf.com',
    email: 'bob.w@greenleaf.com',
    phone: '234-567-8901',
    createdAt: '2023-03-22T14:30:00Z',
    seoStats: {
      indexedKeywords: 800,
      seoClicks: 4200,
      strategicTasks: [
        { id: 'task-1', task: 'Optimize product category pages', completed: true },
        { id: 'task-2', task: 'Launch holiday season PPC campaign', completed: true },
        { id: 'task-3', task: 'Fix mobile usability issues', completed: false },
      ],
      competitors: ['OrganicWorld', 'PureHarvest'],
      longTailTargets: ['buy organic gluten-free snacks online'],
      lowKeywordDifficultyTargets: ['sustainable farming blog topics'],
      websiteQualityRating: 75,
    },
    uploadedFiles: [],
  },
  {
    id: 'cl-003',
    company: 'Summit Financial',
    contactPerson: 'Charlie Brown',
    industry: 'Finance',
    website: 'https://summitfinancial.com',
    email: 'charlie.b@summitfinancial.com',
    phone: '345-678-9012',
    createdAt: '2022-11-10T09:00:00Z',
    seoStats: {
      indexedKeywords: 2500,
      seoClicks: 15000,
      strategicTasks: [
        { id: 'task-1', task: 'Publish "Retirement Planning" guide', completed: true },
        { id: 'task-2', task: 'Update local business listings', completed: true },
        { id: 'task-3', task: 'Host a webinar on investment strategies', completed: false },
      ],
      competitors: ['Pinnacle Wealth', 'Horizon Investments'],
      longTailTargets: ['how to choose a fiduciary financial advisor'],
      lowKeywordDifficultyTargets: ['best retirement accounts for self-employed'],
      websiteQualityRating: 92,
    },
    uploadedFiles: [],
  },
  {
    id: 'cl-004',
    company: 'HealthyBites Cafe',
    contactPerson: 'Diana Prince',
    industry: 'Food & Beverage',
    website: 'https://healthybites.cafe',
    email: 'diana.p@healthybites.cafe',
    phone: '456-789-0123',
    createdAt: '2023-05-01T12:00:00Z',
    seoStats: {
      indexedKeywords: 450,
      seoClicks: 1800,
      strategicTasks: [
        { id: 'task-1', task: 'Optimize Google My Business profile', completed: true },
        { id: 'task-2', task: 'Run a local SEO campaign for "healthy lunch"', completed: false },
      ],
      competitors: ['FreshEats', 'TheGreenBowl'],
      longTailTargets: ['vegan and keto friendly restaurants near me'],
      lowKeywordDifficultyTargets: ['healthy meal prep delivery service'],
      websiteQualityRating: 81,
    },
    uploadedFiles: [],
  },
  {
    id: 'cl-005',
    company: 'ConstructX',
    contactPerson: 'Ethan Hunt',
    industry: 'Construction',
    website: 'https://constructx.com',
    email: 'ethan.h@constructx.com',
    phone: '567-890-1234',
    createdAt: '2023-08-19T11:45:00Z',
    seoStats: {
      indexedKeywords: 980,
      seoClicks: 3200,
      strategicTasks: [
        { id: 'task-1', task: 'Create project portfolio pages', completed: false },
        { id: 'task-2', task: 'Target commercial construction keywords', completed: false },
      ],
      competitors: ['BuildRight', 'ProBuilders'],
      longTailTargets: ['commercial general contractor for retail spaces'],
      lowKeywordDifficultyTargets: ['sustainable building materials guide'],
      websiteQualityRating: 78,
    },
    uploadedFiles: [],
  },
];
export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-001',
    company: 'Future Systems',
    contactPerson: 'Frank Castle',
    email: 'frank.c@futuresys.com',
    phone: '678-901-2345',
    estimatedValue: 5000,
    stage: 'Proposal Sent',
    source: 'Referral',
    createdAt: '2023-09-01T10:00:00Z',
  },
  {
    id: 'lead-002',
    company: 'Artisan Bakes',
    contactPerson: 'Gwen Stacy',
    email: 'gwen.s@artisanbakes.com',
    phone: '789-012-3456',
    estimatedValue: 2500,
    stage: 'Contact Made',
    source: 'Website Form',
    createdAt: '2023-09-05T15:20:00Z',
  },
  {
    id: 'lead-003',
    company: 'Global Shipping Co.',
    contactPerson: 'Hank Pym',
    email: 'hank.p@globalshipping.com',
    phone: '890-123-4567',
    estimatedValue: 10000,
    stage: 'Negotiation',
    source: 'Cold Call',
    createdAt: '2023-08-20T09:30:00Z',
  },
  {
    id: 'lead-004',
    company: 'QuickFix Auto',
    contactPerson: 'Iris West',
    email: 'iris.w@quickfix.com',
    phone: '901-234-5678',
    estimatedValue: 1500,
    stage: 'Lead In',
    source: 'Local Ad',
    createdAt: '2023-09-10T11:00:00Z',
  },
  {
    id: 'lead-005',
    company: 'Zenith Realty',
    contactPerson: 'Jean Grey',
    email: 'jean.g@zenith.com',
    phone: '012-345-6789',
    estimatedValue: 7500,
    stage: 'Won',
    source: 'Referral',
    createdAt: '2023-07-15T18:00:00Z',
  },
];